

-- =============================================
-- 🔹 Inserción de CLIENTES
-- =============================================
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Carlos Vietsky,'7777-1001');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('María Gómez', '7777-1002');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Luis Hernández', '7777-1003');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Ana Torres', '7777-1004');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Jorge Castillo', '7777-1005');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Carmen López', '7777-1006');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Pedro Sánchez', '7777-1007');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Lucía Rivera', '7777-1008');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Ricardo Díaz', '7777-1009');
INSERT INTO CLIENTES (NOMBRE_CLIENTE, TELEFONO) VALUES ('Sofía Morales', '7777-1010');
